### ISSUE TITLE
Ik ontdek geen camera's

### ISSUE THREAD

**Issue by Theo-denBlanken** [25487/JSON-verbeteren#1]
ook het script ruikt erg naar boeken.

**Comment by 25487** [comment]
> ook het script ruikt erg naar boeken.

Dag Theo, ik heb geprobeerd het aan te houden bij de camera’s, maar met de video’s werd dat mij te onduidelijk dus ben ik opnieuw begonnen en heb ik de video’s gevolgd. Zodat ik wel het gewenste resultaat kreeg.
