### ISSUE TITLE
weer gelijk aan Joshua

### ISSUE THREAD

**Issue by Theo-denBlanken** [25487/JSON-verbeteren#2]
dan is het beter niets in te leveren

**Comment by 25487** [comment]
> dan is het beter niets in te leveren

Dag Theo, 
Ik heb de video’s gevolgd die u had opgegeven voor de opdracht, ik heb hier ook vervolgens uren aan gewerkt om hem te optimaliseren zodat het daadwerkelijk goed werkte. Ik heb alle code die ik heb gebruikt van uw video’s.

**Comment by 25487** [comment]
> dan is het beter niets in te leveren

Dit kunt u ook zien aan het aantal commits die ik heb gepushed naar de repository
